name: wokflow

on:
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Uptime 
        run: uptime
      - name: Checking User Details
        run: "who am i"